---
# bastion-network tasks

- name: Set ip_forward sysctl
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/ipv4.forward.conf
    state: present
    reload: true

- name: Allow natted traffic through bastion lab interface
  shell: |
    iptables -t nat -A POSTROUTING -o {{ bastion_lab_interface }} -j MASQUERADE

- name: Start/Enable frr routing
  systemd:
    state: started
    enabled: true
    name: frr

- name: Setup control-plane node network
  nmcli:
    type: ethernet
    conn_name: "{{ bastion_control_plane_interface }}"
    ifname: "{{ bastion_control_plane_interface }}"
    ip4: 198.18.10.1/24
    state: present

# Stop/disable iptables / firewalld
# Setup remote worker node vlaned networks
