---
# Separate tasks to populate static network configuration

- name: Assemble controlplane static network config
  set_fact:
    item_network_config: "{{ lookup('template', 'controlplane.nmstate.yml.j2') }}"
  when:
    - item in groups['controlplane']

- name: Assemble bm static network config
  set_fact:
    item_network_config: "{{ lookup('template', 'worker.nmstate.yml.j2') }}"
  when:
    - item in groups['worker']

# AI doesn't support vlan configuration just yet
# - name: Assemble remote workers static network config
#   set_fact:
#     item_ips_config: "{{ lookup('template', 'remoteworker.nmstate.yml.j2') }}"
#   when:
#     - item in groups['remoteworker']

- name: Add {{ item }} ip config
  set_fact:
    static_network_config: "{{ static_network_config + [ item_network_config ] }}"
