---
# create-inventory tasks
#
# First machine is bastion
# Following 3 machines are controlplane nodes
# Remaining are remote worker nodes

- name: Download ocpinventory.json
  uri:
    url: "http://{{ lab_quads_host }}/cloud/{{ scalelab_cloud }}_ocpinventory.json"
    return_content: true
  register: ocpinventory

- name: Set inventory variables
  set_fact:
    bastion_machine: "{{ ocpinventory.json.nodes[0].pm_addr | replace('mgmt-','') }}"
    controlplane0: "{{ ocpinventory.json.nodes[1].pm_addr }}"
    controlplane1: "{{ ocpinventory.json.nodes[2].pm_addr }}"
    controlplane2: "{{ ocpinventory.json.nodes[3].pm_addr }}"
    controlplane0_network_mac: "{{ ocpinventory.json.nodes[1].mac | first }}"
    controlplane1_network_mac: "{{ ocpinventory.json.nodes[2].mac | first }}"
    controlplane2_network_mac: "{{ ocpinventory.json.nodes[3].mac | first }}"
    bmc_user: "{{ ocpinventory.json.nodes[0].pm_user }}"
    bmc_password: "{{ ocpinventory.json.nodes[0].pm_password }}"

- name: Get controlplane0 lab mac address
  uri:
    url: "https://{{ lab_foreman_host }}/api/hosts/{{ controlplane0 | replace('mgmt-','') }}"
    force_basic_auth: yes
    user: "{{ scalelab_cloud }}"
    password: "{{ bmc_password }}"
    validate_certs: false
  register: controlplane0_foreman_data

- name: Set controlplane0 lab mac addresses
  set_fact:
    controlplane0_lab_mac: "{{ item.mac }}"
  with_items: "{{ controlplane0_foreman_data.json.interfaces }}"
  when: item.primary|bool

- name: Get controlplane1 lab mac address
  uri:
    url: "https://{{ lab_foreman_host }}/api/hosts/{{ controlplane1 | replace('mgmt-','') }}"
    force_basic_auth: yes
    user: "{{ scalelab_cloud }}"
    password: "{{ bmc_password }}"
    validate_certs: false
  register: controlplane1_foreman_data

- name: Set controlplane1 lab mac addresses
  set_fact:
    controlplane1_lab_mac: "{{ item.mac }}"
  with_items: "{{ controlplane1_foreman_data.json.interfaces }}"
  when: item.primary|bool

- name: Get controlplane2 lab mac address
  uri:
    url: "https://{{ lab_foreman_host }}/api/hosts/{{ controlplane2 | replace('mgmt-','') }}"
    force_basic_auth: yes
    user: "{{ scalelab_cloud }}"
    password: "{{ bmc_password }}"
    validate_certs: false
  register: controlplane2_foreman_data

- name: Set controlplane2 lab mac addresses
  set_fact:
    controlplane2_lab_mac: "{{ item.mac }}"
  with_items: "{{ controlplane2_foreman_data.json.interfaces }}"
  when: item.primary|bool

- name: Set ocpinventory rwn nodes
  set_fact:
    ocpinventory_rwn_nodes: "{{ ocpinventory.json.nodes[4:] }}"

- name: Place inventory file named {{ scalelab_cloud }}.local into inventory directory
  template:
    src: inventory.j2
    dest: "{{ playbook_dir }}/inventory/{{ scalelab_cloud }}.local"
