---
# Sample vars file
################################################################################
# Create Inventory playbook vars
################################################################################
# Which scale lab cloud are we deploying on
scalelab_cloud:

lab_quads_host:
lab_foreman_host:

# Network configuration for control-plane nodes
lab_dns:
controlplane_lab_interface: eno1np0
controlplane_network_interface: ens1f0
controlplane_network: 198.18.10.0/24
controlplane_network_prefix: 24
controlplane_network_gateway: "{{ controlplane_network | next_nth_usable(1) }}"
controlplane_network_api: "{{ controlplane_network | next_nth_usable(3) }}"
controlplane_network_ingress: "{{ controlplane_network | next_nth_usable(4) }}"

# Network for remote worker nodes
rwn_vlan_start: 100
rwn_network_start: 198.18.16.0
rwn_network_prefix: 30
rwn_network_mask: 255.255.255.252
rwn_network_interface: ens1f1
rwn_lab_interface: eno1np0

################################################################################
# Setup Bastion playbook vars
################################################################################
bastion_cluster_config_dir: /root/rwn

openshift_client_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/
kubeburner_url: https://github.com/cloud-bulldozer/kube-burner/releases/download/v0.9/kube-burner-0.9-Linux-x86_64.tar.gz

bastion_lab_interface: eno1np0
bastion_control_plane_interface: ens1f0

http_store_path: /opt/http_store/data/

coreos_installer_image: quay.io/coreos/coreos-installer:v0.7.0

assisted_service_image: quay.io/ocpmetal/assisted-service:v1.0.17.3
assisted_installer_image: quay.io/ocpmetal/assisted-installer:v1.0.17.3
assisted_installer_agent_image: quay.io/ocpmetal/assisted-installer-agent:v1.0.17.3
assisted_installer_controller_image: quay.io/ocpmetal/assisted-installer-controller:v1.0.17.3
assisted_service_gui_image: quay.io/ocpmetal/ocp-metal-ui:v1.0.17.3
assisted_postgres_image: quay.io/ocpmetal/postgresql-12-centos7

rhcos_image: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live.x86_64.iso

################################################################################
# Deploy playbook vars
################################################################################
assisted_installer_host: example.com
assisted_installer_port: 8090

http_store_host: example.com
http_store_port: 8080

cluster_name: rwn
openshift_version: "4.6"
# Either OpenShiftSDN or OVNKubernetes
networktype: OpenShiftSDN
base_dns_name: example.com

controlplane_etcd_on_nvme: false
controlplane_nvme_device: /dev/nvme0n1
controlplane_localstorage_configuration: false
controlplane_localstorage_device: /dev/sdb
controlplane_localstorage_lv_count: 10
controlplane_localstorage_lv_size: 100G
controlplane_prometheus_retention_period: 15d

cluster_network_cidr: 10.128.0.0/14
service_network_cidr: 172.30.0.0/16
machine_network_cidr: 10.198.6.0/24

vip_dhcp_allocation: false
ntp_server: clock.redhat.com

ssh_private_key_file: ~/.ssh/id_rsa
ssh_public_key_file: ~/.ssh/id_rsa.pub
pull_secret: "{{ lookup('file', '../pull_secret.txt') }}"

discovery_iso_file_name: ai-discovery.iso

autorules_rule:
  name: .*worker.*
  labels:
  - node-role.kubernetes.io/worker

rwn_install_device: /dev/sda
