---
global:
  writeToFile: true
  metricsDirectory: collected-metrics
  measurements:
  - name: podLatency
    esIndex: kube-burner

  indexerConfig:
    enabled: false
    esServers: [https://user:password@es-instance.example.org:9200]
    insecureSkipVerify: true
    defaultIndex: kube-burner
    type: elastic

jobs:
  - name: ran
    jobType: create
    jobIterations: 12
    qps: 20
    burst: 40
    namespacedIterations: true
    cleanup: true
    namespace: ran
    podWait: false
    waitWhenFinished: true
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
    - objectTemplate: objectTemplates/ran-deployment-selector.yml
      replicas: 1
      inputVars:
        image: gcr.io/google_containers/pause-amd64:3.0
        resources:
          requests:
            cpu: 29
            memory: 120Gi
          limits:
            cpu: 29
            memory: 120Gi
        shared_selectors: 100
        unique_selectors: 100
        unique_selector_offset: 6
