---
global:
  writeToFile: true
  metricsDirectory: collected-metrics
  measurements:
    - name: podLatency
      esIndex: kube-burner

  indexerConfig:
    enabled: false
    esServers: [https://user:password@es-instance.example.org:9200]
    insecureSkipVerify: true
    defaultIndex: kube-burner
    type: elastic

jobs:
  - name: cleanup-ran
    jobType: delete
    waitForDeletion: true
    qps: 10
    burst: 20
    objects:

    - kind: Deployment
      labelSelector: {kube-burner-job: kube-burner-job}
      apiVersion: apps/v1

    - kind: Namespace
      labelSelector: {kube-burner-job: kube-burner-job}
      apiVersion: v1
