---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ran-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ran-{{ .Iteration }}-{{ .Replica }}
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: ran-{{ .Iteration }}-{{ .Replica }}
    spec:
      containers:
      - name: pause-pod
        image: {{ .image }}
        resources:
          requests:
            cpu: {{ .resources.requests.cpu }}
            memory: {{ .resources.requests.memory }}
          limits:
            cpu: {{ .resources.limits.cpu }}
            memory: {{ .resources.limits.memory }}
      nodeSelector:
        rwn: "true"
