---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ran-ds-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
spec:
  selector:
    matchLabels:
      app: ran-ds-{{ .Iteration }}-{{ .Replica }}
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: ran-ds-{{ .Iteration }}-{{ .Replica }}
    spec:
      containers:
      - name: pause-pod
        image: {{ .image }}
        resources:
          requests:
            cpu: {{ .resources.requests.cpu }}
            memory: {{ .resources.requests.memory }}
          limits:
            cpu: {{ .resources.limits.cpu }}
            memory: {{ .resources.limits.memory }}
      nodeSelector:
        rwnu-{{ .Iteration }}: "true"
