---
# Create inventory playbook
#
# Example Usage:
#
# ansible-playbook ansible/create-inventory.yml
#

- name: Create inventory from a scalelab cloud
  hosts: localhost
  gather_facts: false
  vars_files:
  - vars/all.yml
  - vars/lab.yml
  roles:
  - validate-vars
  - create-inventory
